### ISSUE TITLE
Device Naming

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1117]
## Device Naming
- User clicked on 'Get Started' on https://github.com/digidem/CoMapeo-mobile/issues/100
- User is invited to name their device
- User cannot proceed to CoMapeo without naming their device
- User successfully names their device
- User lands on the Map screen

# 1
<img width="351" alt="Screen Shot 2023-10-02 at 11 38 39 AM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/af889ade-269d-4e5f-a6b3-fff50caa9bf9">

## Todo
- [ ] Display screen # 1 as designed
- [ ] Make 'Add a Name for our device' mandatory field to be able to  `Add Name` 
- [ ] Do not display tooltip
- [ ] Create `Add Name` button

# 2
<img width="345" alt="Screen Shot 2023-10-02 at 11 38 57 AM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/58ea576d-0c6f-43d8-b9eb-48d8dab0ddc7">

## Todo
- [ ] Display screen as designed
- [ ] Display device name as entered on screen # 1
- [ ] Create `Go to Map` button
- [ ] Display the map screen when clicking the `Done` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1069-4606&mode=design&t=7vnK6OIYo99rronU-0

## Copydeck
https://docs.google.com/spreadsheets/d/18x135fNGqwryXcBoJGvtNSJJMHuPB48Vp0o1l16UyzY/edit?usp=sharing
