### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1118]
## Settings
- Update the settings menu by re-organizing the menu

## 1 Settings
<img width="348" alt="Screen Shot 2023-10-02 at 1 42 11 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/bc6f1a3a-5388-445e-8b33-9e0c5d7f9e78">

## 2 Project Settings

<img width="327" alt="Screen Shot 2023-10-02 at 1 45 14 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/c8229a77-edc7-475a-b9cf-98127142d934">

## Todo
- [ ] Display the menu as designed for Settings
- [ ] Create a `Create or Join Project` button 
- [ ] Display `Create a new project or join existing one` under `Create or Join Project`  button 
- [ ] Create a `Project Settings` button
- [ ] Display `Categories, Config, Icons`  under `Project Settings` button
- [ ] Create a `App Settings` button
- [ ] Display `Language, Security, Coordinates` under  `App Settings`  button
- [ ] Create a `Experimental Feature` button
- [ ] Create a `About Mapeo` button
- [ ] Create a `Privacy Policy` button

- [ ] Display the menu as designed for Project Settings
- [ ] Create a `Device Name` button 
- [ ] Create a `Configuration` button 
- [ ] Create a `Your Team` button 

-
## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1075-5095&mode=design&t=cbKc4ALXPNtDgAFh-0
