### ISSUE TITLE
Project Invite / Create project

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1119]
## Project invite
- User was in https://github.com/digidem/mapeo-mobile/issues/1118. and clicked on 'Create or join a project'
- User follows flow to create a project

# 1.1 User not on project
<img width="349" alt="Screen Shot 2023-10-02 at 11 45 29 AM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/02b7217b-9112-4ddd-aefc-66843241f2f6">

## Todo
- [ ] Display text box with **What is a Project?** copy
- [ ] Create `Create a Project /Start a new CoMapeo Project` button
- [ ] Create `Join a Project/ Join an existing CoMapeo Project` button

# 1.2 User on project
<img width="339" alt="Screen Shot 2023-10-02 at 11 51 03 AM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/81c56a4c-01af-4ef2-aee7-e7df46a29c39">

## Todo
- [ ] Display text box with **What is a Project?** copy
- [ ] Remove `Create a Project /Start a new CoMapeo Project` button
- [ ] Display text box with **You are already on a project. To create a new Project you must uninstall and reininstall CoMapeo**
- [ ] Create `Join a Project/ Join an existing CoMapeo Project` button

# 2 
<img width="229" alt="Screen Shot 2023-09-25 at 11 40 29 AM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/a630512d-4cdd-461a-9e13-802729252cbb">

## Todo
- [ ] Display`Enter a name for the project` title
- [ ] Create mandatory text field, max 100 characters
- [ ] Use usual error message in the text field (@ErikSin  maybe add more details here)
- [ ] Create `Advanced project settings` dropdown button
- [ ] Display `Import config` when `Advanced project settings` is open
- [ ] When clicking `Import config` display file chooser
- [ ] Create `Create Project`  button

# 3 
<img width="239" alt="Screen Shot 2023-09-25 at 11 40 48 AM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/bbc9d265-9572-4802-aef1-4a47fca0b40e">

## Todo
- [ ] Display success message "XXX Project create"
- [ ] Create `Invite Devices`  button
- [ ] Create `Go to Map`  button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1070-4687&mode=design&t=ypas7TLUlTe7pRjw-0

## Copydeck
https://docs.google.com/spreadsheets/d/1kpoU-mr-fJyxbAxERqrhC2IyRd3T64YEs8fUDzbAFQY/edit?usp=sharing
