### ISSUE TITLE
Leave Project

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1120]
## Leave Project
- User has joined a project and wishes to leave it
- User is on the *Your Team* screen and clicks on `Leave Project`
- If user is a Coordinator, and they are more than 1 coordinator in the project, follow the flow below
- If user is a Coordinator, and they are the only Coordinator follow this https://github.com/digidem/mapeo-mobile/issues/1131

# 1 
<img width="319" alt="Screen Shot 2023-10-02 at 2 32 37 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/75c5c9d5-9c1f-4c64-9850-b0dda95ed7a1">

## ToDo
- [ ] Display **You are already on a project**
- [ ] Display **You've been invited to join**
- [ ] Add mandatory checkbox next to **I understand I will be deleting all data from Project Name from my device**
- [ ] User cannot leave project is box is unchecked
- [ ] Create `Leave Project` button
- [ ] Create `Cancel` button

# 2 Error state
<img width="307" alt="Screen Shot 2023-10-02 at 2 35 51 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/9ae4e05d-0676-4df6-b91b-78bd5748150d">

## Todo
- [ ] If user tries to click on **Leave project** without checking the box, display error message

# 3 Leaving project progress
<img width="680" alt="Screen Shot 2023-10-02 at 6 25 33 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/29422ed6-d90c-4c95-bab2-697ddd907ba2">

- [ ] Display progress bar as designed
- [ ] Note from Sabella "After this reached 100% wait a beat and then show them the Success Bottom sheet" see ## 4 https://github.com/digidem/mapeo-mobile/issues/1130

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1099-856&mode=design&t=ypas7TLUlTe7pRjw-0

## Copydeck
https://docs.google.com/spreadsheets/d/1QXPIdnOFIRAk41hfnGBMw1zEafD8Vp1ZwqDm4XiUR3g/edit#gid=588765348
