### ISSUE TITLE
Join Project

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1121]
## Join Project
- User was in https://github.com/digidem/mapeo-mobile/issues/1118. and clicked on 'Create or join a project'
- User clicked on Join a project

<img width="208" alt="Screen Shot 2023-10-04 at 2 51 37 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/6e64cc1b-b980-43a5-aa77-0c946af6563d">

## Todo
- [ ] Display page
- [ ] Display text title **How to join a project**
- [ ] Display text explaining how to join a project, copy tbd, for now add  **To join a project find a Coordinator of the project you wish to join. Tell them your device name and the Coordinator will send you an invite.**
- [ ] Create `Go back` button

## Design
https://docs.google.com/spreadsheets/d/1kpoU-mr-fJyxbAxERqrhC2IyRd3T64YEs8fUDzbAFQY/edit#gid=583501046

## Copydeck
https://docs.google.com/spreadsheets/d/1kpoU-mr-fJyxbAxERqrhC2IyRd3T64YEs8fUDzbAFQY/edit#gid=583501046
