### ISSUE TITLE
Device Invite

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1124]
## Your team
- User was on https://github.com/digidem/mapeo-mobile/issues/1122 and clicked on **Your team**
- User is on a project and can see the project and available devices, leave project
- User cannot leave project if they are the only coordinator ( if clicked - pop up warning)
- User clicks on **Invite Device**

# 1
<img width="314" alt="Screen Shot 2023-10-02 at 1 52 09 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/d3d0c8eb-7f66-4e6d-8c59-cf9effd3fbc0">

## Todo
- [ ] Display screen as designed
- [ ] Create a `Invite Device` button 
- [ ] Display text **Coordinators**
- [ ] Display text **Coordinators can invite devices, edit and delete data, and manage project details.** 
- [ ] Display users own device 
- [ ] Create a `Leave Project` button 
- [ ] Display text **Participants**
- [ ] Display text **Participants can take and share observations. They cannot manage users or project details.** 
- [ ] When no participants on project, display text **No Participants have been added to this project**

# 2 
<img width="209" alt="Screen Shot 2023-09-25 at 4 35 17 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/95c0e333-b241-4f5f-8f13-88f7653e607b">

## Todo
- [ ] Display **Select Device to Invite** as header
- [ ] Display text **Not seeing a device? Make sure both devices are on the same wifi network. Make sure both devices are on the same version of Mapeo**
- [ ] Display available devices by their Device Name
- [ ] Disregad **Learn More** button

# 3 
<img width="210" alt="Screen Shot 2023-09-25 at 4 35 48 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/3a0ac9e3-05ba-4cf9-92e5-f29b27dbee31">

## Todo
- [ ] Display **Select a Role** as header
- [ ] Display text **You are selecting a role for this device:**
- [ ] Create a `Participant` button 
- [ ] Display text **As a Participant this device can take and share observations. They cannot manage users or project details.**
- [ ] Create a `Coordinator` button 
- [ ] Display text **As a Coordinator this device can invite users, and manage project details.**

# 4 
<img width="206" alt="Screen Shot 2023-09-25 at 4 36 04 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/b50e302c-ae21-4bd2-82d0-6929caee06b9">

## Todo
- [ ] Display **Review Invitation** as header
- [ ] Display text **You are inviting:**
- [ ] Create a `Coordinator` button 
- [ ] Create a `Send Invite` button 

# 5 
<img width="318" alt="Screen Shot 2023-10-02 at 1 59 17 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/8f076130-685f-4128-8d24-a523aba2a6ac">

## Todo
- [ ] Display text **Waiting for device to accept invite**
- [ ] Display time invite was sent
- [ ] Create a `Cancel Invite` button 

# 6
<img width="309" alt="Screen Shot 2023-10-02 at 2 00 13 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/fae8a72d-06fb-4d6e-b050-65989fd1690e">

## Todo
- [ ] Display text **Invite Accepted**
- [ ] Display device details
- [ ] Create a `Add Another Device` button 
- [ ] If clicked `Add Another Device` button , go back to # 2
- [ ] Create a `Close` button 

- [ ] When device is invited, display device name under Particpant or Coordinator 

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1075-5095&mode=design&t=cbKc4ALXPNtDgAFh-0

## Copydeck
https://docs.google.com/spreadsheets/d/1l4_ImeOzXbnqsCG4BGxdH0elXFdm73e3RL_ME75wWT0/edit#gid=980984343
