### ISSUE TITLE
Sync flow / success - Screens Only

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1128]
## Sync flow / success
- User has created or joined a project
- User tries to sync

# 1 Pre-sync / No devices clicked on Sync
<img width="235" alt="Screen Shot 2023-09-25 at 8 01 37 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/329c31fb-53e8-429d-b0ed-a271049b147f">

## Todo
- [ ] Display the menu as designed 
- [ ] Display **Project name**
- [ ] Display **Your device name is XXXX**  
- [ ] If devices are nearby on local wifi, display **XXXX Devices nearby/connected**  
- [ ] If no user has clicked on `Sync`, display **No devices are syncing**
- [ ] Create a `Sync` button

# 2 Pre-sync/ Devices clicked on Sync
<img width="245" alt="Screen Shot 2023-09-25 at 8 02 07 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/2069857b-59cd-4fb3-81e7-bee7453caa7b">

## Todo
- [ ] If a user/users clicked on `Sync`, display **XXXX Devices Waiting to Sync with you**

# 3 Syncing
<img width="237" alt="Screen Shot 2023-09-25 at 8 02 28 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/f8ed3a74-b9b1-47e3-b08a-0b156386d1b9">

## Todo
- [ ] Display **Syncing with XXXX Devices**  
- [ ] Adjust **XXXX Devices nearby/connected** if more devices joined the local wifi
- [ ] Create progress bar as designed, display **Syncing**  and percentage
- [ ] Create a `Stop Sync` button

# 4 Syncing done
<img width="233" alt="Screen Shot 2023-09-25 at 8 02 45 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/97067026-07b2-4241-908b-8808d6bb3fc8">

## Todo
- [ ] Display **Up to Date! No data to Sync**  
- [ ] Create a `You’re all caught up!` button
- [ ] If `You’re all caught up!` button is clicked, add glowing color red

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1068-4024&mode=design&t=lw81UhsBQKXEHyHD-0

## Copydeck
https://docs.google.com/spreadsheets/d/1Oi3cgEEE-XxQJ11JSwOJRjvUBlgmNSMxvV0XHrSJoG0/edit#gid=199798000

**Comment by ErikSin** [comment]
@gmaclennan since the mapeo-core-next documentation is not up to date, can you let me know what methods I will need for this flow?
