### ISSUE TITLE
Invite Received

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1130]
## Invite Received
- User is **anywhere** on CoMapeo and recieves an invitation to join a project
- User is either already on a project or not

## Technical Spec
- Use a listener at the app.tsx level
- Create the modal at app.tsx level
- The Listener should be turned on and off based off an `enabled:boolean` state. This state should be help in global state in a zustand store, and can be toggled from any component

## 1
<img width="318" alt="Screen Shot 2023-10-02 at 2 07 49 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/30ad1ac3-cec3-4d89-9903-fab7b8e72d87">

## Todo
- [ ] Create bottom nav drawer
- [ ] Display *Join Project XX**
- [ ] Display **This will remove all Project Name data from your device**
- [ ] Create `Decline invite` button
- [ ] Create `Join` button

## 2 User already on a project
<img width="341" alt="Screen Shot 2023-10-02 at 2 18 10 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/f8439afa-8ea9-4517-9a2f-b8787889ca86">

## Todo
- [ ] Display *Join Project XX**
- [ ] Display **You are on Project XX**
- [ ] Display **To join a new project you must leave your current one.**
- [ ] Create `Leave Current Project` button
- [ ] Create `Go Back` button

## 4 Success
<img width="319" alt="Screen Shot 2023-10-02 at 2 21 42 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/480a5024-ae81-46c4-82c6-918da0716d36">

## Todo
- [ ] Display **Success! You have joined X**
- [ ] Create `Go to Map` button
- [ ] Create `Go to Sync` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1196-1914&mode=design&t=cbKc4ALXPNtDgAFh-0

## Copydeck
https://docs.google.com/spreadsheets/d/1tRrPiQqb5owaSs-DA68AoN6DzeayyN4Y8lhebb19dhc/edit#gid=980984343

**Comment by macandrow** [comment]
Added frames to show the notification Desktop receives when they receive an invite. Pulling from where this originated, which was the OTF work. https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1247%3A153&mode=design&t=LAyLbSmJ1snN9LyP-1
