### ISSUE TITLE
Edit device name

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#1132]
## Edit device name
- User has gone through onboarding and has named their device
- User wishes to edit their device name
- User goes to Settings - Project Settings - Device Name

## 1
<img width="314" alt="Screen Shot 2023-10-02 at 7 01 02 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/6e542680-5f0a-44f5-b80b-375dcb6a3593">

## Todo
- [ ] Display **Your Device Name**
- [ ] Create edit button using pen icon at the top right

## 2
<img width="316" alt="Screen Shot 2023-10-02 at 7 01 18 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/83eb71b4-b8a6-45f7-b2e4-6c42fe659300">

## Todo
- [ ] When pen icon clicked, change to checkmark icon
- [ ] Display text box with device name
- [ ] Display max characters /60
- [ ] Note from Sabella : If user taps edit, show save button top right, Edit label and field. If a user makes changes to the name field but doesn’t tap Save we are going to show them a dialog box

## 3
<img width="315" alt="Screen Shot 2023-10-02 at 7 01 41 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/a0241e23-99c7-42b3-a7c2-0f92350e73e2">

## Todo
- [ ] Display pop-up if user didn't click on Save and clicked elswhere
- [ ] Create `Continue editing` button
- [ ] Create `Discard changes` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1200-69&mode=design&t=xfOwkkUA7kBhB7vK-0

## Copydeck
https://docs.google.com/spreadsheets/d/1-ToQImFcHK6f0TpPJgpDIJf92kD1pIq8Cz6uH9meoVM/edit#gid=1868132643
