### ISSUE TITLE
Mm Release v5.1 

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-mobile#370]
This issue is to discuss features and bug fixes to include in the next release (v5.1). I will keep this first comment updated as a list of proposed features and fixes to include, add a link to the Issue, PR or commit for each feature/task, and mark each as "done" when it is merged in the develop branch. If we decide it's not feasible to include one of these features in the 

**Features**
- [x] Add settings screen to show App version #368 
- [x] Keep auto-device name consistent between restarts #369
- [ ] Changing field from single-select to multi-select doesn't crash things
- [x] Default offline map 

**Bug Fixes**
- [x] Cancelling edit shows "discard edit"

**Internal Improvements**
- [x] Update to React Native v0.62 #366
- [x] Update to React Navigation v4 #367

**Later**
- [ ] Add intro screens #234
- [ ] Add link to intro screens from settings
- [ ] Update build scripts from Manyver.se #325 
- [ ] Peer-to-peer update #314 
- [ ] Improved export
- [ ] GPS radar #365

**Comment by okdistribute** [comment]
Maybe also https://github.com/digidem/mapeo-mobile/issues/457?
